### ISSUE TITLE
A wish: Minimal Cypress-Free "demo2a" for PSoC4

### ISSUE THREAD

**Issue by Mecrisp** [kiml/PSOC_compiler#3]
I am very glad that you conquered the PSoC5 completely bare-metal, without config and without Cypress parts, and I wish to do exactly the same for a CY8C4245 for porting my native code Forth compiler, Mecrisp-Stellaris, to it. I tried hard to switch a wire, but I did not suceed - I suppose that I might have missed an essential register or two:

[minimal-psoc4.txt](https://github.com/kiml/PSOC_compiler/files/251977/minimal-psoc4.txt)

May I kindly ask you if you could help with a "demo2a" for Psoc4 ?

Best wishes from Germany,
Matthias Koch
mecrisp.sourceforge.net

**Comment by lowfatcomputing** [comment]
Hello Matthias,

Page 6 of this document has some assembly language snippets for toggling pins on the PSoC5 and PSoC3:

http://www.cypress.com/file/141051/download

```
@ Load register address (PRT0_PRT)
ldr r2, =0x4000510A
@ Set drive mode
mov r3, 0x0C
@ Store drive mode in register
str r3, [r2]
@ Load register address (PRT0_DR)
ldr r2, =0x40005100
@ Set pin data
mov r3, 0x01
@ Store pin data in register
str r3, [r2]
```

I think you need to [set the drive mode](https://github.com/kiml/PSOC_compiler/blob/master/common/psoc/psoc_registers.h#L346) to 0x0C for `STRONG` output to drive an LED. I don't have a PSoC4 but I think it's the same just check the [the register maps](https://github.com/kiml/PSOC_compiler/blob/master/common/psoc/psoc_registers.h#L270).

I used this [FX2LP board](https://sigrok.org/wiki/Lcsoft_Mini_Board) with my [PSoC 5LP Schmartboard](http://schmartboard.com/schmartboard-psoc-5lp-development-board-with-boot-loaded-psoc-5lp-ic-710-0008-05/) because [this post](http://dangerousprototypes.com/forum/viewtopic.php?f=56&t=3105#p48104) says there are some strict timing requirements so not all JTAGs will work.

Since then [a $10 PSoC 5LP board](http://www.cypress.com/documentation/development-kitsboards/cy8ckit-059-psoc-5lp-prototyping-kit-onboard-programmer-and) has been made available with a built-in programmer. I think this PSoC 5LP board is similar to [your PSoC4 board if I remember correctly](http://www.cypress.com/documentation/development-kitsboards/psoc-4-cy8ckit-049-4xxx-prototyping-kits). I don't have one though and I'm not sure what kind of hardware this new 5LP board's programmer has.

Best Regards,
Andreas Wagner

**Comment by Mecrisp** [comment]
Finally, here comes the minimal bare metal blinky for PSOC4.

[Cypress-Blinky.zip](https://github.com/kiml/PSOC_compiler/files/1338864/Cypress-Blinky.zip)

Many thanks to Richard Klingler.
